version: '3.3'
services:
  nginx:
    image: 'nginx:1.15-alpine'
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - wordpress
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './data/nginx:/etc/nginx/conf.d'
      - './data/certbot/conf:/etc/letsencrypt'
      - './data/certbot/www:/var/www/certbot'
    command: "/bin/sh -c 'while :; do sleep 6h & wait 13216{!}; nginx -s reload; done & nginx -g \"daemon off;\"'" #nginx reload every 6h background and but still run foreground to refresh new cert
  #######################################################################################################################
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    container_name: certbot
    volumes:
      - './data/certbot/conf:/etc/letsencrypt'
      - './data/certbot/www:/var/www/certbot'
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait 13216{!}; done;'"  #check cert renewal for every 12 hours
  ##########################################################################################################################
  db:
    image: 'mysql:5.7'
    container_name: mysql
    volumes:
      - 'db_data:/var/lib/mysql'
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      #MYSQL_ROOT_PASSWORD: TESTINGPWD
      MYSQL_DATABASE: clouddays_DB
      MYSQL_USER: ${SQLUSER}
      MYSQL_PASSWORD: ${SQLPASSWORD}
  ##############################################################################################################################
  wordpress:
    depends_on:
      - db
    image: 'wordpress:latest'
    container_name: wordpress
    volumes:
      - 'wordpress_data:/var/www/html'
    restart: always
    environment:
      WORDPRESS_DB_HOST: 'db:3306'
      WORDPRESS_DB_USER: ${SQLUSER}
      WORDPRESS_DB_PASSWORD: ${SQLPASSWORD}
      WORDPRESS_DB_NAME: clouddays_DB
volumes:
  db_data: {}
  wordpress_data: {}